UNIT_EMPTY = 2000
UNIT_NUM = 1000
UNIT_UNKNOWN = 3000
UNIT_BOOM = 4000
UNIT_SAFE = 5000

COMMAND_FAILD = "GAME OVER"
COMMAND_SUCCE = "SUCCEFUL"
COMMAND_NORM = "NORMAL"

DEBUG_MODE = False

# 用于最后的显示
DISPLAY_BOOM = "&"
DISPLAY_EMPTY = " "

# 用于游戏过程中
DISPLAY_UNKNOWN = "?"
DISPLAY_NUM = "0"
DISPLAY_FLAG = "*"

LOG_FILE = "log.txt"
MSG_BUFF_SIZE = 4

CPP_ENUMERATE = False
GAUSS_ENUMERATE = True

